name: Back end infrastructure only deploymnet
on:
  push:
      branches:
        - main
      paths:
        - devops/deploy/backend/**
  workflow_dispatch:
env:
  NODE_VERSION: "18"
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_AKI }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SAC }}  
  TRACKBOSS_ENVIRONMENT_NAME: trackboss
  COGNITO_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID }}
  COGNITO_POOL_ID: ${{ secrets.COGNITO_POOL_ID }}
  CLUB_EMAIL: ${{ secrets.CLUB_EMAIL }}
  SQUARE_TOKEN: $${{ secrets.SQUARE_TOKEN }}
  SQUARE_LOCATION: $${{ secrets.SQUARE_LOCATION }}
jobs:
  backend-cdk-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Specify Node version
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Run CDK backend deployment
      run: bash devops/deploy/backend/deployBackendInfra.sh $HOME/work/trackboss/trackboss
