name: Front end deployment
on:
  push:
      branches:    
        - main
      paths:
       - frontend/
  workflow_dispatch:
env:
  NODE_VERSION: "16"
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_AKI }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SAC }}  
  TRACKBOSS_ENVIRONMENT_NAME: trackboss
  COGNITO_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID }}
  COGNITO_POOL_ID: ${{ secrets.COGNITO_POOL_ID }}
  CLUB_EMAIL: ${{ secrets.CLUB_EMAIL }}
jobs:
  frontend-cdk-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Specify Node version
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Run CDK frontend deployment
      run: bash devops/deploy/frontend/deployFrontEnd.sh $TRACKBOSS_ENVIRONMENT_NAME $HOME/work/trackboss/trackboss
  # backend-build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2
  #   - name: Specify Node version
  #     uses: actions/setup-node@v2
  #     with:
  #       node-version: ${{ env.NODE_VERSION }}
  #   - name: Install modules
  #     run: npm ci
  #   - name: Run TS Build
  #     run: npm run build
  #   - name: Create Distributable
  #     run: npm run dist
  #   - name: Create Artifact
  #     uses: actions/upload-artifact@v3
  #     with:
  #         name: backend-build
  #         path: dist
  # frontend-build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2
  #   - name: Specify Node version
  #     uses: actions/setup-node@v2
  #     with:
  #       node-version: ${{ env.NODE_VERSION }}
  #   - name: Install modules
  #     run: cd frontend && npm ci
  #   - name: Run Frontend Build
  #     run: cd frontend && npm run build-ci
  #   - name: Create Artifact
  #     uses: actions/upload-artifact@v3
  #     with:
  #         name: frontend-build
  #         path: frontend/build

