name: PR
on:
  - pull_request
  - workflow_dispatch
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: |
        npm ci
        (cd frontend && npm ci)
    - name: Run ESLint
      run: npx eslint .