name: PR
on:
  - pull_request
  - workflow_dispatch
env:
  NODE_VERSION: "16"
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Specify Node version
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install modules
      run: |
        npm ci
        (cd frontend && npm ci)
    - name: Run ESLint
      run: npx eslint .
  jest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Specify Node version
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install modules
      run: |
        npm ci
        (cd frontend && npm ci)
    - name: Run Jest
      run: |
        npm run ci-test
        (cd frontend && npm run ci-test)
