name: Test DB
on:
  - workflow_dispatch
env:
  NODE_VERSION: "16"
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_AKI }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SAC }}
  PROJECT_ROOT: ${{ secrets.PROJECT_ROOT }}
  TRACKBOSS_ENVIRONMENT_NAME: trackboss
jobs:
  test-db-destroy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Specify Node version
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: CDK destroy test database
      run: cd devops/deploy/backend && npm ci && npx cdk destroy trackboss-testdb
